name: Deploy Admin Panel

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/admin/**'
      - '.github/workflows/admin-panel.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_ADMIN_TOKEN }}
        
      - name: Build Admin Panel
        run: |
          cd frontend/admin
          npm install
          npm run build
          
      - name: Deploy Admin Panel to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_ADMIN_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ADMIN_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_ADMIN_PROJECT_ID }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NODE_ENV: production
          FRONTEND_URL: https://odaville.com
          ADMIN_URL: https://admin.odaville.com
          JWT_SECRET: ${{ secrets.JWT_SECRET }} 